<script lang="ts">
  import { _ } from "svelte-v4-i18n";

  import { Button, ListItem } from "fluent-svelte";
  import Separator from "$shared/Separator/Separator.svelte";

  import ListGroup from "$shared/Items/ListGroup/ListGroup.svelte";

  import AddIcon from "@fluentui/svg-icons/icons/add_16_regular.svg?raw";

  import { createEventDispatcher } from "svelte";
  import ItemListPlaceholder from "$shared/Placeholders/ItemListPlaceholder/ItemListPlaceholder.svelte";
  const dispatch = createEventDispatcher();

  export let groups = [];

  export let defaultGroup;
  export let loading = false;
  export let selectedGroup;
  export let compact = false;

  let _groups;

  $: _groups = groups.filter(
    (group) => !group.flags.isAutoGenerated && !group.flags.isHidden
  );

  let onSelect = (group) => {
    if (group.id != selectedGroup.id) {
      dispatch("select", {
        group: group,
      });
    }
  };

  function addNewGroup() {
    dispatch("addgroup");
  }
</script>

<div class="group-list">
  <ListItem
    href="#"
    compact={true}
    selected={defaultGroup.id == selectedGroup.id}
    on:click={() => onSelect(defaultGroup)}
  >
{defaultGroup.title}
    <svg
      slot="icon"
      xmlns="http://www.w3.org/2000/svg"
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
    >
      <path
        d="M10.5045 3.11661C10.1924 2.93379 9.80585 2.93379 9.49372 3.11661L3.48483 6.63608C2.82456 7.02281 2.82557 7.97759 3.48667 8.36292L9.49556 11.8652C9.80676 12.0466 10.1915 12.0466 10.5027 11.8652L16.5116 8.36292C17.1727 7.97759 17.1737 7.02281 16.5134 6.63608L10.5045 3.11661ZM9.49372 4.27551C9.80585 4.09269 10.1924 4.09269 10.5045 4.27551L16.008 7.49896L10.5027 10.7078C10.1915 10.8892 9.80676 10.8892 9.49556 10.7078L3.99023 7.49896L9.49372 4.27551ZM3.07073 9.65002L9.50875 13.2725C9.81322 13.4438 10.185 13.4438 10.4895 13.2725L16.9275 9.65004C17.1145 10.0883 16.9757 10.6395 16.5116 10.91L10.5027 14.4123C10.1915 14.5937 9.80676 14.5937 9.49556 14.4123L3.48667 10.91C3.02254 10.6395 2.88376 10.0883 3.07073 9.65002ZM3.07073 12.103L9.50875 15.7254C9.81322 15.8967 10.185 15.8967 10.4895 15.7254L16.9275 12.103C17.1145 12.5412 16.9757 13.0924 16.5116 13.3629L10.5027 16.8653C10.1915 17.0467 9.80676 17.0467 9.49556 16.8653L3.48667 13.3629C3.02254 13.0924 2.88376 12.5412 3.07073 12.103Z"
        fill="currentFill"
      />
    </svg>
  </ListItem>
  {#if _groups.length > 0}
    <Separator horizontal={true} />
  {/if}
  <div class="groups">
    {#if loading}
      {#each Array(10) as i}
        <ItemListPlaceholder {compact} />
      {/each}
    {:else}
      {#each _groups as group (group.id)}
        <ListGroup
          {group}
          href="#"
          {compact}
          selected={group.id == selectedGroup.id}
          on:click={() => onSelect(group)}
        />
      {/each}
    {/if}
  </div>
  {#if !loading}
    <Button id="add-group-button" variant="accent" on:click={addNewGroup}>
      {@html AddIcon}
      &nbsp; {$_("nav.create_group")}
    </Button>
  {/if}
</div>

<style lang="scss">
  @use "GroupList.scss";
</style>
